version: '3.5'
services:
  jsp-twitter-api:
    container_name: jsp-twiiter-api
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IS_PRODUCTION: 'true'
